[dev]
  framework = "vite"
  autoLaunch = true

[build]
  command = 'npm run build'
  environment = {NODE_VERSION = '20'}
  publish = 'dist'

[[redirects]]
  force = true
  status = 200
  from = '/api/*'
  to = '/api/:splat'

[[redirects]]
  status = 200
  from = '/*'
  to = '/index.html'
