[dev]
  command = "npm run client:dev"
  targetPort = 5173
  autoLaunch = true

[build]
  command = "npm run build"
  environment = { NODE_VERSION = "22" }
  publish = "dist"

[functions]
  directory = "netlify/functions"

# API to Netlify Functions (must come first to take precedence)
# Netlify routing works top down and matches the first redirect and stops matching
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/getData/:splat"
  status = 200
  force = true

# SPA routing - serve index.html for all routes (otherwise /cv-branch will 404!)
# Essentially the default route - the API route has not been matched, return the homepage.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200