[dev]
  framework = "vite"
  autoLaunch = true

[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/netlify/functions/api/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'
