[dev]
  framework = "vite"
  autoLaunch = true

[build]
command = 'npm run build'
environment = {NODE_VERSION = '20'}
publish = 'dist'

[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/api/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'
