[dev]
  command = "npm run client:dev"
  targetPort = 5173
  autoLaunch = true

[build]
  command = "npm run build"
  environment = { NODE_VERSION = "20" }
  publish = "dist"

[functions]
  directory = "netlify/functions"

# API to Netlify Functions
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/getData/:splat"
  status = 200

# SPA routing - serve index.html for all routes (otherwise /cv-branch will 404!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200