[dev]
  command = "npm run client:dev"
  targetPort = 5173
  autoLaunch = true

[build]
  command = "npm run build"
  environment = { NODE_VERSION = "20" }
  publish = "dist"

[functions]
  directory = "netlify/functions"