[dev]
  command = "npm run client:dev"
  targetPort = 5173
  autoLaunch = true

[build]
  command = "npm run build"
  environment = { NODE_VERSION = "20" }
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/getData/:splat"
  status = 200
  force = true